# Generated by Django 5.2.13 on 2026-04-16 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_index', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.testpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.telegramuser')),
            ],
        ),
    ]
