# Generated by Django 5.2.14 on 2026-05-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_testsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь Telegram', 'verbose_name_plural': 'Пользователи Telegram'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс (сум)'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='has_free_attempt',
            field=models.BooleanField(default=True, verbose_name='Есть бесплатная попытка'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум статус'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Премиум активен до'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм'),
        ),
    ]
