# Generated by Django 5.2.14 on 2026-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_telegramuser_options_telegramuser_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='free_attempts_left',
            field=models.IntegerField(default=1, verbose_name='Оставшиеся бесплатные попытки'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_premium_bool',
            field=models.BooleanField(db_column='is_premium', default=False, verbose_name='Премиум статус (устарело)'),
        ),
    ]
